export const ActionsTypes = {
  FETCH_FILMS: "FETCH_FILMS",
  FETCH_DETAIL_FILM: "FETCH_DETAIL_FILM",
  REMOVE_DETAIL_FILM: "REMOVE_DETAIL_FILM",
  FETCH_CREDIT_FILM: "FETCH_CREDIT_FILM",
  REMOVE_CREDIT_FILM: "REMOVE_CREDIT_FILM",
  FETCH_REVIEW_FILM: "FETCH_REVIEW_FILM",
  REMOVE_REVIEW_FILM: "REMOVE_REVIEW_FILM",
}